# basic config
title: Nick Maclean
description: >- # this means to ignore newlines until "baseurl:"
  Personal portfollio website for Nick Maclean. 

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nicolasmaclean.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# socials
email: nicolasimaclean ( at ) gmail.com
email_link: nicolasimaclean@gmail.com

github_username:  nicolasmaclean
github_link: https://github.com/nicolasmaclean

linkedin_username: nick maclean
linkedin_link: https://linkedin.com/in/nick-maclean


# file paths
pictureurl: "/_assets/pictures/"
portfoliourl: "/_assets/portfolio/"


# Build settings
markdown: kramdown
them: null

include: [_pages, _assets, _scripts, _portfolio]
sass:
  style: compressed
  sass_dir: _sass


# Front Matter Defaults
defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
      permalink: /blog/:categories/:title/
  -
    scope:
      path: _portfolio
    values:
      is_portfolio: true
      layout: project
      permalink: /portfolio/:folder/
  -
    scope:
      type: pages
      path: _pages
    values:
      layout: default